POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "gttx",
  "password": "asdfasdf"
}

###
GET http://localhost:8080/api/test/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJndHR4IiwiaWF0IjoxNjQ4MjEwODA2LCJleHAiOjE2NDgyMTI2MDZ9.L0bZ7BIH89olr8IojF7h6nas2CPC_MYosz9hDx2325WE44ks_eln8e3TpxZrDIsSbE079qjVzmswxqWXAU-YAg


###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstName": "gurkan",
  "lastName": "turkarslan",
  "username": "gttx",
  "email": "gtx@mail.com",
  "password": "asdfasdf",
  "role": ["DEV", "STUDENT", "MODERATOR"]
}


###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstName": "gt",
  "lastName": "tt",
  "username": "qtdev",
  "email": "1qw@email.com",
  "password": "password",
  "role": ["DEV", "STUDENT"]
}


###
GET http://localhost:8080/api/test/user
Accept: application/json

###
GET http://localhost:8080/api/test/all
Accept: application/json

###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "qtdev",
  "password": "password"
}

<> 2022-03-15T141842.200.json
