INSERT INTO ROLE(ROLE_TYPE) SELECT 'USER' FROM DUAL WHERE NOT EXISTS
    (SELECT ROLE_TYPE FROM ROLE WHERE ROLE_TYPE = 'USER');

INSERT INTO ROLE(ROLE_TYPE) SELECT 'STUDENT' FROM DUAL WHERE NOT EXISTS
    (SELECT ROLE_TYPE FROM ROLE WHERE ROLE_TYPE = 'STUDENT');

INSERT INTO ROLE(ROLE_TYPE) SELECT 'INSTRUCTOR' FROM DUAL WHERE NOT EXISTS
    (SELECT ROLE_TYPE FROM ROLE WHERE ROLE_TYPE = 'INSTRUCTOR');

INSERT INTO ROLE(ROLE_TYPE) SELECT 'MODERATOR' FROM DUAL WHERE NOT EXISTS
    (SELECT ROLE_TYPE FROM ROLE WHERE ROLE_TYPE = 'MODERATOR');

INSERT INTO ROLE(ROLE_TYPE) SELECT 'DEV' FROM DUAL WHERE NOT EXISTS
    (SELECT ROLE_TYPE FROM ROLE WHERE ROLE_TYPE = 'DEV');