-- INSERT INTO ROLE(ROLE_TYPE) VALUES ( 'USER' ),
--                                    ( 'INSTRUCTOR' ),
--                                    ( 'MODERATOR' ),
--                                    ( 'STUDENT' ),
--                                    ( 'DEV' );