POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "gtx",
  "password": "asdfasdf"
}

###
GET http://localhost:8080/api/test/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJndHgiLCJpYXQiOjE2NDgwMjEzMTMsImV4cCI6MTY0ODAyNDkxM30.ODf7i4olqmH5apmeN-O6y2QSygR3UNshSmcDZX3ivBSsy6Mc91QS455k5AWJC0ImFIAE-T1OVrHF5mP9B_FR_Q


###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstName": "gt",
  "lastName": "tt",
  "username": "qtdev",
  "email": "1qw@email.com",
  "password": "password",
  "role": ["DEV", "STUDENT"]
}


###
GET http://localhost:8080/api/test/user
Accept: application/json

###
GET http://localhost:8080/api/test/all
Accept: application/json

###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "qtdev",
  "password": "password"
}

<> 2022-03-15T141842.200.json
