POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "qtx",
  "password": "asdfasdf"
}

###
GET http://localhost:8080/api/test/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJxdHgiLCJpYXQiOjE2NDgwMjUzODAsImV4cCI6MTY0ODAyODk4MH0.0QlYclq7NYcQ0AKWlyEWEFPcRxl1AsLHDnQdWJU1Lyg-Fhj8Cfqj_zGWiIXguWL83793OQA5SSqX1UMcIOfWrA


###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstName": "gurkan",
  "lastName": "turkarslan",
  "username": "qtx",
  "email": "gtx@mail.com",
  "password": "asdfasdf",
  "role": ["DEV", "STUDENT", "MODERATOR"]
}

###
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstName": "gt",
  "lastName": "tt",
  "username": "qtdev",
  "email": "1qw@email.com",
  "password": "password",
  "role": ["DEV", "STUDENT"]
}


###
GET http://localhost:8080/api/test/user
Accept: application/json

###
GET http://localhost:8080/api/test/all
Accept: application/json

###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "qtdev",
  "password": "password"
}

<> 2022-03-15T141842.200.json
